fieldLayouts:
  6a52ea9d-7054-473e-9b7c-93ad21472b74:
    tabs:
      -
        fields:
          3d10df47-f48c-4ae8-a6fd-1663ffe6db6e: # Body
            required: false
            sortOrder: 2
          037a5f54-21d8-4b39-b38d-0e7af880f8a2: # Heading
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: page404
name: '404 - Page Not Found'
sortOrder: 1
