fieldLayouts:
  39ed494f-8708-43f4-abdc-720dc72afcf7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: photos
hasUrls: true
name: 'General Photos'
settings:
  path: uploads/photos
sortOrder: 3
type: craft\volumes\Local
url: uploads/photos
