fieldLayouts:
  61cd6a25-5f7d-4a8d-8b19-61a8fd5d0b01:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 3d10df47-f48c-4ae8-a6fd-1663ffe6db6e # Body
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 20af4766-fe55-42f8-9d36-2ab967f5d1e7 # SEO Description
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ba29f542-5277-4f31-940d-1e7f36817ccf # SEO Keywords
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2f37e135-42dc-4728-9899-b1c8a1bd538d # SEO Robots
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3e44c697-2501-4e56-af5a-b9ca5afff38b # SEO Title
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: pastEvents
hasTitleField: false
name: 'Past Events'
section: 634f71e7-b201-460b-a50e-9820ea06c829
sortOrder: 1
titleFormat: '{section.name|raw}'
