fieldLayouts:
  96dfecab-bcce-488c-9034-cb994173ca4c:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 906f4fea-87c9-4022-84ba-4dcb41fa0e74
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b33387e8-9db5-45ed-976a-1b0d4372f22c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 98f17359-9b77-492f-85b3-a731451de13d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 00d05235-8eef-4c30-a4bb-0569264b309d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 10192265-6990-4588-a974-797d82034ccc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 284cdcec-672c-4074-a89f-a0eed974fba3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f40d0fd7-6cec-47fa-9535-ab15ed4732c5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ce6c438f-5e52-4d86-b133-a1d85aac17f7
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 20af4766-fe55-42f8-9d36-2ab967f5d1e7
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ba29f542-5277-4f31-940d-1e7f36817ccf
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2f37e135-42dc-4728-9899-b1c8a1bd538d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3e44c697-2501-4e56-af5a-b9ca5afff38b
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: speakers
hasTitleField: true
name: Speakers
section: 320c4965-45f5-4543-84d7-606ed8ab334f
sortOrder: 1
titleFormat: null
