contentColumnType: string
fieldGroup: a9c8a941-15b1-466e-a1a3-6aa013e1d989
handle: contactCopy
instructions: ''
name: 'Contact Copy'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: '1'
  columnType: text
  configFile: Standard.json
  purifierConfig: ''
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
