contentColumnType: boolean
fieldGroup: bb1cc818-9a89-4344-82ca-4d6c1d8dbfa7 # Events
handle: headlineTalk
instructions: ''
name: 'Headline Talk'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
