columnSuffix: null
contentColumnType: string
fieldGroup: a9c8a941-15b1-466e-a1a3-6aa013e1d989
handle: links
instructions: ''
name: 'Quick Link'
searchable: false
settings:
  contentTable: '{{%matrixcontent_links}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
