contentColumnType: string
fieldGroup: a9c8a941-15b1-466e-a1a3-6aa013e1d989
handle: partners
instructions: ''
name: Partners
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'section:8c7b1d14-0b67-434f-add4-9ea397f6c251'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
