contentColumnType: string
fieldGroup: a9c8a941-15b1-466e-a1a3-6aa013e1d989
handle: partnerLogo
instructions: ''
name: 'Partner Logo'
searchable: true
settings:
  defaultUploadLocationSource: 'volume:50fb2e47-fb7e-4214-9e47-e4285eff585a' # Speakers
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  singleUploadLocationSource: 'volume:95b71215-725c-454f-8f8d-4ab133b7f9f8' # Partners
  singleUploadLocationSubpath: ''
  sources: '*'
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
