contentColumnType: boolean
fieldGroup: 05fb3290-dc67-4027-b719-be4b594fee26 # SEO
handle: seoRobots
instructions: 'Switch off if you don''t want search engines to index'
name: 'SEO Robots'
searchable: true
settings:
  default: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
