contentColumnType: text
fieldGroup: bb1cc818-9a89-4344-82ca-4d6c1d8dbfa7
handle: speakerAudio
instructions: 'https://w.soundcloud.com/player/?url=REPLACE'
name: 'Speaker Audio'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/AUDIOIDHERE'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
