contentColumnType: string
fieldGroup: bb1cc818-9a89-4344-82ca-4d6c1d8dbfa7 # Events
handle: speakers
instructions: ''
name: Speakers
searchable: true
settings:
  contentTable: '{{%matrixcontent_speakers}}'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
