contentColumnType: string
fieldGroup: a9c8a941-15b1-466e-a1a3-6aa013e1d989
handle: squareImageOverlays
instructions: ''
name: 'Square Image Overlays'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:50fb2e47-fb7e-4214-9e47-e4285eff585a' # Speakers
  defaultUploadLocationSubpath: ''
  limit: '2'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:77fe10b2-e220-4768-8ca3-7d4b3a714d33' # General Photos
  singleUploadLocationSubpath: ''
  sources: '*'
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
