contentColumnType: text
fieldGroup: bb1cc818-9a89-4344-82ca-4d6c1d8dbfa7 # Events
handle: titoEventName
instructions: ''
name: 'Tito Event Name'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'i.e. mkgn-22'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
