contentColumnType: text
fieldGroup: bb1cc818-9a89-4344-82ca-4d6c1d8dbfa7
handle: twitterHandle
instructions: ''
name: 'Twitter Handle'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: davidhughes
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
