enableVersioning: true
handle: pastEvents
name: 'Past Events'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  73c38894-ebbc-4d2e-960d-f1077a2ce423:
    enabledByDefault: true
    hasUrls: true
    template: pages/_events-listing
    uriFormat: past
type: single
