defaultPlacement: end
enableVersioning: true
handle: quickLinks
name: 'Quick Links'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  73c38894-ebbc-4d2e-960d-f1077a2ce423:
    enabledByDefault: true
    hasUrls: true
    template: quick-links
    uriFormat: quick-links
type: single
