enableVersioning: true
handle: quotes
name: Quotes
propagationMethod: all
siteSettings:
  73c38894-ebbc-4d2e-960d-f1077a2ce423:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
